language: go
go:
  - "1.10"

install: skip

jobs:
  include:
    - stage: test
      before_install:
        - go get github.com/mattn/goveralls
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - npm install -g snyk
      script:
        - go test ./... -v -cover -covermode=count -coverprofile=c.out
        # upload coverage stats
        - $GOPATH/bin/goveralls -coverprofile=c.out -service=travis-ci || exit 0
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT || exit 0
        - snyk test
      after_success:
        - snyk monitor

    - &deploy-stage
      stage: build and deploy
      sudo: required
      script:
        # build
        - >
          docker build -t podlike:$DOCKER_TAG         \
            --build-arg CC=$CC                        \
            --build-arg CC_PKG=$CC_PKG                \
            --build-arg CC_GOARCH=$CC_GOARCH          \
            --build-arg VERSION=$TRAVIS_BRANCH        \
            --build-arg GIT_COMMIT=$TRAVIS_COMMIT     \
            --build-arg BUILD_TIMESTAMP=$(date +%s)   \
            .
      after_success:
        - |
          echo ${DOCKER_PASSWORD} | docker login --username "rycus86" --password-stdin
          if [ "$TRAVIS_BRANCH" == "master" ]; then
              docker tag podlike:${DOCKER_TAG} rycus86/podlike:${DOCKER_TAG}
              docker push rycus86/podlike:${DOCKER_TAG}
          else
              docker tag podlike:${DOCKER_TAG} rycus86/podlike:${TRAVIS_BRANCH}-${DOCKER_TAG}
              docker push rycus86/podlike:${TRAVIS_BRANCH}-${DOCKER_TAG}
          fi
      env:
        - DOCKER_TAG=amd64

    - <<: *deploy-stage
      env:
        - DOCKER_TAG=armhf
        - CC=arm-linux-gnueabihf-gcc
        - CC_PKG=gccgo-arm-linux-gnueabihf
        - CC_GOARCH=arm

    - <<: *deploy-stage
      env:
        - DOCKER_TAG=aarch64
        - CC=aarch64-linux-gnu-gcc
        - CC_PKG=gccgo-aarch64-linux-gnu
        - CC_GOARCH=arm64

    - stage: manifest
      sudo: required
      script:
        - |
          if [ "$TRAVIS_BRANCH" != "master" ]; then
              sed -i "s#rycus86/podlike:#rycus86/podlike:${TRAVIS_BRANCH}-#" manifest.yml
              sed -i "s#rycus86/podlike:${TRAVIS_BRANCH}-latest#rycus86/podlike:${TRAVIS_BRANCH}#" manifest.yml
          fi
        - echo ${DOCKER_PASSWORD} | docker login --username "rycus86" --password-stdin
        - curl -fsSL https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 > ./manifest-tool
        - chmod +x ./manifest-tool
        - ./manifest-tool push from-spec manifest.yml

